//
// Created by crocdialer on 10/1/18.
//

#pragma once

#include "vierkant/Device.hpp"
#include "vierkant/Framebuffer.hpp"
#include "vierkant/Image.hpp"

namespace vierkant
{

class SwapChain
{
public:
    static constexpr uint32_t max_frames_in_flight = 3;

    struct acquire_image_result_t
    {
        uint32_t image_index = 0;
        VkResult result = VK_ERROR_UNKNOWN;
        VkSemaphore image_available = VK_NULL_HANDLE;
        VkSemaphore render_finished = VK_NULL_HANDLE;
    };

    struct create_info_t
    {
        //! handle for a VkSurfaceKHR to create the SwapChain for
        VkSurfaceKHR surface = VK_NULL_HANDLE;

        //! requested multisampling
        VkSampleCountFlagBits num_samples = VK_SAMPLE_COUNT_1_BIT;

        //! request vertical synchronisation (cap fps to refresh rate)
        bool use_vsync = true;

        //! request an HDR swapchain-format and colorspace
        bool use_hdr = false;

        //! peak display-luminance in cd/m², used for HDR output
        float peak_nits = 1000.f;

        //! luminance of SDR reference-white in cd/m², used for HDR output
        float paper_white_nits = 203.f;

        //! optional framebuffer_size, overriding the size queried from VkSurfaceKHR,
        //! NOTE: should not be required and mainly used to workaround a buggy display-stack
        std::optional<VkExtent2D> framebuffer_size;
    };

    SwapChain() = default;

    /**
     * @brief   Construct a new SwapChain
     *
     * @param   device              handle for the vierkant::Device to create the SwapChain with
     * @param   create_info         a create_info_t struct
     */
    SwapChain(DevicePtr device, const create_info_t &create_info);

    SwapChain(SwapChain &&other) noexcept;

    SwapChain(const SwapChain &other) = delete;

    ~SwapChain();

    SwapChain &operator=(SwapChain other);

    /**
     * @brief       Acquire the next image from the SwapChain
     *
     * @param       timeout     optional timeout in nanoseconds
     * @return      a acquire_image_result_t struct, grouping all return-params.
     */
    acquire_image_result_t acquire_next_image(uint64_t timeout = std::numeric_limits<uint64_t>::max());

    /**
     * @brief   submit the current SwapChain-image to the presentation queue and update frame-indices
     * @return  the VkResult generated by vkQueuePresentKHR
     */
    VkResult present();

    /**
     * @return  handle for the managed VkSwapchainKHR
     */
    [[nodiscard]] VkSwapchainKHR handle() const { return m_swap_chain; }

    /**
     * @return  handle for the device
     */
    [[nodiscard]] DevicePtr device() const { return m_device; }

    /**
     * @return  a reference for the contained array of Framebuffers
     */
    std::vector<vierkant::Framebuffer> &framebuffers() { return m_framebuffers; }

    vierkant::Framebuffer &current_framebuffer() { return m_framebuffers[m_swapchain_image_index]; }

    /**
     * @return  a reference for array of SwapChain-Images
     */
    [[nodiscard]] const std::vector<vierkant::ImagePtr> &images() const { return m_images; }

    /**
     * @return  the VkExtent2D (size) of the SwapChain-Images
     */
    [[nodiscard]] const VkExtent2D &extent() const { return m_extent; }

    /**
     * @return  the VkSampleCountFlagBits stating the number of samples per pixel (MSAA)
     */
    [[nodiscard]] VkSampleCountFlagBits sample_count() const { return m_num_samples; }

    /**
     * @return  a flag indicating if vertical synchronization is used
     */
    [[nodiscard]] bool v_sync() const { return m_use_v_sync; }

    /**
     * @return  a flag indicating if HDR is used
     */
    [[nodiscard]] bool hdr() const
    {
        return m_color_format == VK_FORMAT_A2B10G10R10_UNORM_PACK32 || m_color_format == VK_FORMAT_R16G16B16A16_SFLOAT;
    }

    /**
     * @return  a flag indicating if HDR is supported
     */
    [[nodiscard]] bool hdr_supported() const { return m_hdr_supported; }

    /**
     * @return  peak display-luminance in cd/m², used for HDR output
     */
    [[nodiscard]] float peak_nits() const { return m_peak_nits; }

    /**
     * @return  luminance of SDR reference-white in cd/m², used for HDR output
     */
    [[nodiscard]] float paper_white_nits() const { return m_paper_white_nits; }

    /**
     * @return  the current image index inside the SwapChain
     */
    [[nodiscard]] uint32_t image_index() const { return m_swapchain_image_index; }

    friend void swap(SwapChain &lhs, SwapChain &rhs) noexcept;

    inline explicit operator bool() const { return static_cast<bool>(m_swap_chain); };

private:
    /**
     * @brief   sync_objects_t is a helper struct to bundle synchronization data for the SwapChain
     */
    struct sync_objects_t
    {
        VkSemaphore image_available = VK_NULL_HANDLE;
        VkSemaphore render_finished = VK_NULL_HANDLE;
    };

    void create_framebuffers();

    void create_sync_objects();

    DevicePtr m_device;

    VkSampleCountFlagBits m_num_samples = VK_SAMPLE_COUNT_1_BIT;

    VkSwapchainKHR m_swap_chain = VK_NULL_HANDLE;

    bool m_use_v_sync = true;

    bool m_hdr_supported = false;

    float m_peak_nits = 1000.f;

    float m_paper_white_nits = 203.f;

    std::vector<vierkant::ImagePtr> m_images;

    std::vector<vierkant::Framebuffer> m_framebuffers;

    VkFormat m_color_format = VK_FORMAT_UNDEFINED;

    VkFormat m_depth_format = VK_FORMAT_UNDEFINED;

    VkExtent2D m_extent = {};

    std::vector<sync_objects_t> m_sync_objects;

    acquire_image_result_t m_last_acquired_image = {};

    uint32_t m_current_frame_index = 0;

    uint32_t m_swapchain_image_index = 0;
};

}// namespace vierkant